# Generated by Django 5.0.1 on 2024-03-05 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flat", "0002_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="name",
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
